server:
  port: 8080
spring:
  # 放行的url
  security:
    ignore:
      urls:
        - /server/*
        - /admin/user/login
        - /admin/report
        - /swagger-ui/**
        - /v3/api-docs/**
        - /swagger-resources/**
        - /doc.html
        - /webjars/**
        - /druid/**
        - /favicon.ico
  application:
    name: personal-blog-admin
  profiles:
    include: common-log,common-private-mail,common-datasource,common-json,common-upload,common-security,common-redis-cache
#  data:
#    redis:
#      # 数据库设置为0号数据库
#      database: 0
#      host: 192.168.200.129
#      port: 6379
#  cache:
#    redis:
#      # 指定是否缓存空值。默认情况下，如果一个方法返回了空值（null），则不会将其缓存起来。
#      # 将该配置设置为true，可以缓存空值。
#      cache-null-values: true
#      # 指定是否启用缓存统计。当设置为true时，Spring Boot会收集关于缓存的统计信息，如缓存命中率、缓存请求次数等。
#      enable-statistics: false
#      # 键前缀
#      key-prefix: cache_
#      # 指定缓存过期时间
#      time-to-live: 60s
#      # 指定是否使用全局键前缀
#      use-key-prefix: false
eureka:
  instance:
    prefer-ip-address: true
    hostname: ${spring.application.name}
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    fetch-registry: true
    register-with-eureka: true # fetch-registry 与 register-with-eureka 都为 true 表示即为提供者, 亦为消费者

    # 连接注册中心超时时间, 默认 5, 单位秒, 一般和注册中心服务失效时间配置一致
    eureka-server-connect-timeout-seconds: 10
    # 读取服务列表的超时时间, 默认 8, 单位秒
    eureka-server-read-timeout-seconds: 10
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#jwt:
#  issuer: personal-blog
#  #JWT存储的请求头
#  header: Authorization
#  #令牌前缀
#  prefix: Bearer
#  secret: "dtPhqyaNgQZlFqmTTG9IVKR7923QLmm3R7uAi3OKSeo="
#  expirationTime:
#    access: 1800000
#    refresh: 86400000
