upload:
  mode: oss
  oss:
    url: http://Bucket域名/
    endpoint: OSS配置endpoint
    accessKeyId: OSS配置accessKeyId
    secretAccessKey: OSS配置accessKeySecret
    bucketName: OSS配置bucketName
  minio:
    url: http://minio的ip:9000/
    endpoint: minio配置endpoint
    accesskey: 用户名
    secretKey: 密码
    bucketName: 桶的名称
  qiniu:
    access-key: 七牛配置accessKey
    secret-key: 七牛配置secretKey
    bucket-name: 七牛配置bucketName
    url: http://七牛域名/
    endpoint: 七牛配置endpoint
  local:
    url: 本地路径
spring:
  web:
    resources:
      static-locations: file:${upload.local.url}