spring:
  config:
    import: configserver:http://localhost:8888/
  cloud:
    config:
      profile: dev                # 使用的配置文件环境
      #    记得修改配置${spring.application.name}-upload-private 为${spring.application.name}-upload common-mail-private 为common-mail-public
      name: "${spring.application.name},common-eureka,common-log,common-mail-private,common-datasource,${spring.application.name}-upload-private,common-security,common-redis,common-rabbitmq"
