server:
  port: 8888
spring:
  cloud:
    config:
      server:
        native:
          search-locations: "classpath:/conf,classpath:/conf/personal-blog-admin,classpath:/conf/personal-blog-server,classpath:/conf/personal-blog-eureka,classpath:/conf/personal-blog-gateway"
