server:
  port: 8082
  servlet:
    context-path: /
spring:
  application:
    name: personal-blog-gateway
  cloud:
    gateway:
      routes:
        - id: personal-blog-server

          uri: lb://personal-blog-server
          predicates:
            - Path=/api/**
          filters:
      global-cors: # 全局的跨域处理
        add-to-simple-url-handler-mapping: true # 解决options请求被拦截问题
        corsConfigurations:
          '[/**]':
            allowedOrigins: # 允许哪些网站的跨域请求
              - "http://localhost:8080"
              - "http://localhost:8081"
              - "http://localhost:8083"
              - "http://localhost:8084"
            allowedMethods: # 允许的跨域ajax的请求方式
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*" # 允许在请求中携带的头信息
            allowCredentials: true # 是否允许携带cookie
            maxAge: 360000 # 这次跨域检测的有效期
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
