server:
  port: 8080
spring:
  # 放行的url
  security:
    ignore:
      urls:
        - /swagger-ui.html
        - /admin/blog/**
        - /admin/user/login
        - /admin/
        - /admin/report
        - /swagger-ui/**
        - /v3/api-docs/**
        - /swagger-resources/**
        - /doc.html
        - /webjars/**
        - /druid/**
        - /favicon.ico
  application:
    name: personal-blog-admin
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
swagger:
  url:
    - "http://192.168.200.129:8084/swagger-ui.html"
    - "http://192.168.200.129:8081/swagger-ui.html"