spring:
  config:
    import: configserver:http://192.168.200.129:8888  # 导入Config Server配置
  cloud:
    config:
      profile: prod               # 使用的配置文件环境
      name: "common-log,${spring.application.name}"
