server:
  port: 10086
spring:
  profiles:
    include: common-log
  application:
    name: personal-blog-eureka-server
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    # 防止Eureka启动时注册本身服务
    register-with-eureka: false
    fetch-registry: false
