server:
  port: 8083
spring:
  profiles:
    include: common-datasource
  application:
    name: personal-blog-search
  elasticsearch:
    uris: http://192.168.200.129:9200

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka