spring:
  # 邮件配置
  mail:
    host: smtp.163.com
    # 邮箱发送地址
    username:
    # 邮箱密码
    password:
    port: 465
    properties:
      # 发信人
      from: GeWuYou
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
