server:
  port: 8085
  servlet:
    context-path: /extension
spring:
  application:
    name: personal-blog-extension
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka