spring:
  # 邮件配置
  mail:
    host: smtp.163.com
    # 邮箱发送地址
    username:
    # 邮箱密码
    password:
    port: 465
    properties:
      # 发信人
      from: GeWuYou
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory

upload:
  mode: oss
  oss:
    url: http://Bucket域名/
    endpoint: OSS配置endpoint
    accessKeyId: OSS配置accessKeyId
    secretAccessKey: OSS配置accessKeySecret
    bucketName: OSS配置bucketName
  minio:
    url: http://minio的ip:9000/
    endpoint: http://minio的ip:9000
    accesskey: 用户名
    secretKey: 密码
    bucketName: 桶的名称
